version: '3.8'

services:
  rasch-bot:
    build: .
    container_name: rasch-counter-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_WEBHOOK_HOST=${TELEGRAM_WEBHOOK_HOST}
      - TELEGRAM_WEBHOOK_PORT=${TELEGRAM_WEBHOOK_PORT}
      - TELEGRAM_CERT_FILE=${TELEGRAM_CERT_FILE}
      - TELEGRAM_KEY_FILE=${TELEGRAM_KEY_FILE}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./data:/app/.data
      - ./logs:/app/logs
    ports:
      - "8443:8443"
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8443/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
